DROP TABLE IF EXISTS user;

CREATE TABLE IF NOT EXISTS huser (
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 username TEXT UNIQUE NOT NULL,
 password TEXT NOT NULL,
 email TEXT,
 created_at CURRENT_TIMESTAMP,
 about TEXT,
 karma INTEGER DEFAULT 0
);
 
CREATE TABLE IF NOT EXISTS post(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title TEXT NOT NULL,
  url TEXT,
  body TEXT,
  points INTEGER DEFAULT 0,
  FOREIGN KEY (user_id) REFERENCES huser (id)
);

CREATE TABLE IF NOT EXISTS comment(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  body TEXT NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  points INTEGER DEFAULT 0,
  post_id INTEGER NOT NULL,
  parent_id INTEGER,
  user_id INTEGER NOT NULL,
  username TEXT,
  FOREIGN KEY (user_id) REFERENCES huser (id),
  FOREIGN KEY (post_id) REFERENCES post (id)
);

ALTER TABLE post ADD COLUMN comment_count INTEGER DEFAULT 0;
